import type { Metadata } from "next";
import Link from "next/link";
import { DeviceData } from "@/components/DeviceData";
import { PageHero } from "@/components/PageHero";
import "./about.css";

export const metadata: Metadata = { title: "About | Wordplay" };

const xp = [["+10", "for each lesson you read"], ["+25", "for each activity you finish"], ["+50", "at most per quiz, from your best score"], ["+5", "for coming back on consecutive days"], ["+2", "for each new word you collect in Wordplay World"], ["+10", "for the first star in each Wordplay World mission"], ["+5", "for your first perfect run of a mission"]];
const principles = [["Questions before answers.", "Every chapter opens with a question, because a good question is what makes an AI tool useful."], ["Local by default.", "Progress, drafts, and answers stay on this device unless you export them."], ["People decide.", "Lessons treat AI as a tool to direct and check. You stay responsible for the result."]];
const access = ["Every page works with a keyboard, and a skip link jumps straight to the main content.", "The Motion setting in the footer, or your system preference, swaps 3D and animation for still typography.", "Quiz and activity feedback is written in words, never shown by color alone.", "Quizzes have no timer, and you can retry any of them.", "Body text keeps a contrast ratio of at least 4.5:1 against its background."];

export default function AboutPage() {
  return <><PageHero tone="rose" label="About Wordplay" title="A calm place to learn how AI works." lede="Wordplay is a hands-on AI literacy course for grades 9 to 12: five chapters, activities that run on your device, and no accounts." mark="&" /><section className="shell about-grid" aria-label="How Wordplay works"><article className="about-block" data-reveal="0"><h2>How progress works</h2><p>Progress rewards learning, not speed. Levels and badges mark what you have done without ranking you against anyone.</p><ul className="xp-list">{xp.map(([points, label]) => <li key={label}><strong>{points} XP</strong><span>{label}</span></li>)}</ul></article><article className="about-block" data-reveal="1"><h2>Privacy by design</h2><p>Wordplay has no accounts, learning backend, or analytics. Activities use local rules, not live AI. Progress and prompt drafts stay in this browser. The 3D artwork loads from Spline only when motion is on. Please do not type private information into practice fields.</p></article><article className="about-block" data-reveal="0"><h2>Your progress file</h2><p>My learning can export a versioned JSON file. Import it on another device to pick up where you left off. Prompt drafts are stored separately and are not included. Keep the file private, because it contains your learning history.</p><Link href="/learn" className="text-link">Open My learning <span aria-hidden="true">↗</span></Link></article><article className="about-block" data-reveal="1"><h2>For teachers</h2><p>Ask students to explain an answer, compare an AI output with a source, and discuss the tradeoffs in each scenario. The capstone is a reflection starter, not a grade generator.</p></article></section><DeviceData /><section className="about-principles" aria-labelledby="principles-title"><div className="shell"><h2 id="principles-title">Three rules we designed by.</h2><ol>{principles.map(([title, copy], index) => <li key={title} data-reveal={index}><span>{String(index + 1).padStart(2, "0")}</span><h3>{title}</h3><p>{copy}</p></li>)}</ol></div></section><section className="shell about-access" aria-labelledby="access-title"><div><h2 id="access-title">Accessibility</h2><p>Wordplay is built to meet WCAG 2.1 AA.</p></div><ul>{access.map((item) => <li key={item}>{item}</li>)}</ul></section><section className="shell about-credits" aria-label="Sources and credits"><p>Every lesson cites its sources, and every typeface and tool is credited.</p><Link href="/references" className="button-primary">See the references <span aria-hidden="true">↗</span></Link></section></>;
}
