import Link from "next/link";
import { notFound } from "next/navigation";
import { getModule, modules } from "@/content";
import { ModuleGlyph } from "@/components/ModuleGlyph";
import { SplitText } from "@/components/motion/SplitText";
import { BlurFade } from "@/components/magicui/BlurFade";

export function generateStaticParams() { return modules.map((module) => ({ slug: module.slug })); }

export default function ModulePage({ params }: { params: { slug: string } }) {
  const currentModule = getModule(params.slug); if (!currentModule) notFound();
  return <div className="shell py-32"><Link href="/modules" className="btn-ghost">← All modules</Link><div className="mt-16 grid gap-8 lg:grid-cols-12"><div className="lg:col-span-8"><p className="eyebrow"><span className="mr-3 text-accent">0{modules.findIndex((item) => item.id === currentModule.id) + 1}</span> Module / {currentModule.activity.kind.replace("-", " ")}</p><div className="mt-7 flex items-end gap-6"><ModuleGlyph moduleId={currentModule.id} className="mb-2 h-12 w-12" /><SplitText as="h1" className="font-display text-[clamp(3rem,8vw,7rem)] leading-[.88]">{currentModule.title}</SplitText></div></div><p className="self-end text-lg leading-relaxed text-ink/75 lg:col-start-9 lg:col-span-4">{currentModule.tagline}</p></div><div className="mt-24 grid gap-16 lg:grid-cols-[1fr_280px]"><main><p className="eyebrow">Lessons</p><div className="mt-5 divide-y divide-line border-y border-line">{currentModule.lessons.map((lesson, index) => <BlurFade key={lesson.id} inView delay={index * .04}><Link className="group flex items-center gap-5 py-6 hover:bg-ink hover:px-5 hover:text-paper" href={`/modules/${currentModule.slug}/lessons/${lesson.id}`}><span className="font-mono text-2xl text-ink/75 group-hover:text-paper/50">0{index + 1}</span><span className="flex-1"><strong className="block font-display text-3xl italic">{lesson.title}</strong><span className="mt-1 block font-mono text-[10px] uppercase tracking-wider text-ink/75 group-hover:text-paper/55">{lesson.minutes} min read · {lesson.keyTakeaways.length} takeaways</span></span><span className="font-mono text-2xl">↗</span></Link></BlurFade>)}</div><Link href={`/modules/${currentModule.slug}/activity`} className="mt-12 block border-y border-line py-7 hover:bg-lime hover:px-5"><p className="eyebrow">Interactive activity</p><h2 className="mt-3 font-display text-4xl italic">{currentModule.activity.title}</h2><p className="mt-2 max-w-2xl text-ink/75">{currentModule.activity.intro}</p></Link><Link href={`/modules/${currentModule.slug}/quiz`} className="block border-b border-line py-7 hover:bg-ink hover:px-5 hover:text-paper"><p className="eyebrow">Knowledge check</p><h2 className="mt-3 font-display text-4xl italic">Short quiz</h2><p className="mt-2 text-ink/75">Test your understanding and keep your best score.</p></Link></main><aside className="h-fit border-t border-line pt-5"><p className="eyebrow">Module map</p><p className="mt-5 leading-relaxed text-ink/75">Read each lesson, try the activity, then take the quiz. You need 70% for module completion.</p><p className="mt-8 border-l-2 border-lime pl-4 text-sm leading-relaxed">You can revisit any step and improve your quiz score later.</p></aside></div></div>;
}
