import Link from "next/link";
import { notFound } from "next/navigation";
import { getModule, modules } from "@/content";

export function generateStaticParams() { return modules.map((module) => ({ slug: module.slug })); }

export default function ModulePage({ params }: { params: { slug: string } }) {
  const currentModule = getModule(params.slug); if (!currentModule) notFound();
  return <div className="shell py-12"><Link href="/modules" className="text-sm font-bold text-accent">← All modules</Link><div className="mt-6 max-w-3xl"><span className="text-5xl">{currentModule.icon}</span><h1 className="mt-4 text-4xl font-black">{currentModule.title}</h1><p className="mt-3 text-lg text-slate-600">{currentModule.tagline}</p></div><div className="mt-10 grid gap-8 lg:grid-cols-[1fr_0.35fr]"><div><h2 className="text-2xl font-black">Lessons</h2><div className="mt-4 space-y-3">{currentModule.lessons.map((lesson, index) => <Link className="card flex items-center gap-4 py-4 hover:border-indigo-300" href={`/modules/${currentModule.slug}/lessons/${lesson.id}`} key={lesson.id}><span className="grid h-10 w-10 shrink-0 place-items-center rounded-full bg-indigo-50 font-bold text-accent">{index + 1}</span><span><strong className="block">{lesson.title}</strong><span className="text-sm text-slate-500">{lesson.minutes} min read · {lesson.keyTakeaways.length} takeaways</span></span><span className="ml-auto text-slate-500">→</span></Link>)}</div><Link href={`/modules/${currentModule.slug}/activity`} className="card mt-4 block border-amber-200 bg-amber-50 hover:border-amber-400"><span className="eyebrow text-amber-700">Interactive activity</span><h3 className="mt-2 text-xl font-bold">{currentModule.activity.title}</h3><p className="mt-1 text-sm text-slate-700">{currentModule.activity.intro}</p></Link><Link href={`/modules/${currentModule.slug}/quiz`} className="card mt-4 block hover:border-indigo-300"><span className="eyebrow">Knowledge check</span><h3 className="mt-2 text-xl font-bold">Five-question quiz</h3><p className="mt-1 text-sm text-slate-600">Test your understanding and keep your best score.</p></Link></div><aside className="card h-fit"><p className="eyebrow">Module map</p><p className="mt-4 text-sm text-slate-600">Read each lesson, try the activity, then take the quiz. You need 70% for module completion.</p><div className="mt-5 rounded-xl bg-slate-100 p-4 text-sm"><strong>Tip</strong><p className="mt-1 text-slate-600">You can revisit any step and improve your quiz score later.</p></div></aside></div></div>;
}
