"use client";
import Link from "next/link";
import { modules } from "@/content";
import { useProgress } from "@/state/ProgressProvider";
import { levelFor, nextLevel, progressToNext } from "@/engine/levels";
import { evaluateBadges } from "@/engine/badges";
import { BADGES } from "@/engine/badges";
import { exportProgress } from "@/engine/storage";
import { ProgressBar } from "@/components/ProgressBar";

function modulePercent(moduleId: string, lessons: number, state: ReturnType<typeof useProgress>["state"]) {
  const done = state.completedLessons.filter((key) => key.startsWith(`${moduleId}/`)).length;
  return Math.round(((done + (state.completedActivities.includes(moduleId) ? 1 : 0) + (state.quizBest[moduleId] ?? 0) / 100) / (lessons + 2)) * 100);
}

export default function Dashboard() {
  const { state, reset, importJson } = useProgress();
  const level = levelFor(state.xp); const next = nextLevel(state.xp);
  function upload(event: React.ChangeEvent<HTMLInputElement>) { const file = event.target.files?.[0]; if (!file) return; const reader = new FileReader(); reader.onload = () => importJson(String(reader.result)); reader.readAsText(file); }
  function download() { const link = document.createElement("a"); link.href = URL.createObjectURL(new Blob([exportProgress(state)], { type: "application/json" })); link.download = "ai-compass-progress.json"; link.click(); }
  if (!state.startedAt) return <div className="shell py-12 sm:py-20"><div className="grid items-center gap-10 lg:grid-cols-[1.2fr_0.8fr]"><div><p className="eyebrow">AI Compass · grades 9–12</p><h1 className="mt-4 max-w-3xl text-5xl font-black tracking-tight sm:text-7xl">Find your way through the world of AI.</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-slate-600">Learn how AI works, practice smart prompts, make responsible choices, and design a project you can defend.</p><Link href="/modules" className="button-primary mt-8">Start learning <span className="ml-2">→</span></Link></div><div className="card bg-ink text-white"><p className="text-5xl">🧭</p><h2 className="mt-5 text-2xl font-bold">Your local learning lab</h2><p className="mt-3 text-slate-300">No accounts. No tracking. Progress is saved in your browser and can be exported whenever you want.</p><div className="mt-6 grid grid-cols-2 gap-3 text-center"><div className="rounded-2xl bg-white/10 p-4"><strong className="block font-pixel text-2xl">5</strong><span className="font-pixel text-xs uppercase tracking-wide text-slate-300">modules</span></div><div className="rounded-2xl bg-white/10 p-4"><strong className="block font-pixel text-2xl">20</strong><span className="font-pixel text-xs uppercase tracking-wide text-slate-300">glossary terms</span></div></div></div></div></div>;
  const badges = evaluateBadges(state, modules);
  const overall = Math.round(modules.reduce((sum, module) => sum + modulePercent(module.id, module.lessons.length, state), 0) / modules.length);
  return <div className="shell py-10"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="eyebrow">Welcome back</p><h1 className="mt-2 text-4xl font-black">Your AI Compass</h1></div><div className="flex gap-2"><button className="button-secondary text-sm" onClick={download}>Export</button><label className="button-secondary cursor-pointer text-sm">Import<input type="file" accept="application/json" className="sr-only" onChange={upload} /></label><button className="button-secondary text-sm" onClick={() => { if (window.confirm("Reset all local progress?")) reset(); }}>Reset</button></div></div>
    <div className="mt-8 grid gap-5 lg:grid-cols-[1.4fr_0.6fr]"><div className="card"><div className="flex items-start justify-between gap-4"><div><p className="eyebrow">Level {level.name}</p><p className="mt-2 font-pixel text-3xl font-black">{state.xp} XP</p></div><span className="font-pixel rounded-full bg-amber-100 px-3 py-1 text-sm font-bold uppercase tracking-wide text-amber-800">🔥 {state.streak.count} day streak</span></div><div className="mt-6">{next ? <ProgressBar value={progressToNext(state.xp) * 100} label={`${next.minXp - state.xp} XP to ${next.name}`} /> : <ProgressBar value={100} label="Maximum level reached" />}</div></div><div className="card"><p className="eyebrow">Overall progress</p><p className="mt-2 font-pixel text-4xl font-black">{overall}%</p><p className="mt-2 text-sm text-slate-600">Keep exploring one step at a time.</p></div></div>
    <h2 className="mt-12 text-2xl font-black">Your modules</h2><div className="mt-4 grid gap-4 md:grid-cols-2">{modules.map((module) => { const percent = modulePercent(module.id, module.lessons.length, state); const nextLesson = module.lessons.find((lesson) => !state.completedLessons.includes(`${module.id}/${lesson.id}`)); return <div className="card" key={module.id}><div className="flex items-start justify-between"><span className="text-3xl">{module.icon}</span><span className="font-pixel text-2xl font-black text-slate-500">{percent}%</span></div><h3 className="mt-4 text-xl font-bold">{module.title}</h3><p className="mt-2 text-sm text-slate-600">{module.tagline}</p><div className="mt-5"><ProgressBar value={percent} label="Module progress" /></div><Link href={`/modules/${module.slug}${nextLesson ? `/lessons/${nextLesson.id}` : ""}`} className="button-secondary mt-5 w-full">{nextLesson ? "Continue" : "Review module"} →</Link></div>; })}</div>
    <div className="mt-12 grid gap-5 md:grid-cols-2"><div><h2 className="text-2xl font-black">Badge shelf</h2><div className="mt-4 flex flex-wrap gap-3">{badges.slice(0, 8).map((id) => { const badge = BADGES.find((item) => item.id === id); return <span key={id} title={badge?.description} className="font-pixel rounded-2xl bg-amber-100 px-3 py-2 text-sm font-bold uppercase tracking-wide text-amber-900">{badge?.icon} {badge?.name}</span>; })}</div></div><div><h2 className="text-2xl font-black">Next step</h2><p className="mt-4 text-slate-600">Use the Modules page to read, practice, and quiz your way through the compass.</p><Link href="/modules" className="button-primary mt-4">Browse modules</Link></div></div>
  </div>;
}
