export type GlossaryEntry = { term: string; definition: string };

const entries: [string, string][] = [
  ["AI", "Artificial intelligence: computer systems designed to perform tasks that involve patterns, language, perception, or decisions. A spam filter and a chat assistant are both examples."],
  ["Machine learning", "A method where a system adjusts its internal settings from examples instead of receiving every rule directly from a programmer."],
  ["Model", "A set of learned patterns and settings used to make predictions or generate results. A model is what you get after training."],
  ["Neural network", "A type of model made of many connected layers of simple math units. It is the technology behind most modern image, speech, and language AI."],
  ["LLM", "Large language model: a model trained on huge amounts of text to predict and generate language. Chat assistants are built on LLMs."],
  ["Token", "A small piece of text, such as a word, part of a word, or a punctuation mark. Language models read and write text one token at a time."],
  ["Training data", "The examples used to shape a model's patterns and behavior. Gaps or errors in this data show up later in the model's results."],
  ["Dataset", "An organized collection of examples, such as thousands of labeled photos or messages, used to train or test a model."],
  ["Label", "The correct answer attached to a training example, such as marking a message as spam or a photo as containing a cat."],
  ["Algorithm", "A repeatable set of steps used to solve a problem or process information, like a recipe a computer follows."],
  ["Classifier", "A system that sorts examples into categories, such as spam or not-spam, or which friend appears in a photo."],
  ["Accuracy", "The share of predictions a model gets right. A high overall accuracy can still hide poor results for a smaller group."],
  ["Overfitting", "When a model memorizes its training examples so closely that it performs poorly on new, slightly different examples."],
  ["Fine-tuning", "Extra training that adjusts an existing model for a specific task or style, such as making a chat assistant more polite or more focused on math."],
  ["Generative AI", "AI that creates new text, images, audio, code, or other content instead of only sorting or predicting."],
  ["Chatbot", "A program that holds a conversation in text or speech. Modern chatbots are usually powered by large language models."],
  ["Prompt", "The instruction, question, or context you give an AI tool. A clear prompt states the task, audience, and format you want."],
  ["Context", "Background information that helps a tool understand a task and audience, such as your grade level or the notes you are studying."],
  ["Hallucination", "A plausible-sounding but unsupported or invented AI output, such as a fake quotation or a book that does not exist."],
  ["Prompt injection", "An attempt to manipulate a tool by hiding conflicting instructions inside the text it reads, like a web page that tells an assistant to ignore its rules."],
  ["Verification", "Checking a result against evidence, a calculation you can reproduce, or a trusted source before relying on it."],
  ["Human oversight", "People reviewing, guiding, and taking responsibility for an AI-assisted decision rather than letting the tool decide alone."],
  ["Bias", "A repeated pattern that produces unfair or inaccurate outcomes for certain people or groups, often inherited from training data."],
  ["Fairness", "The practice of evaluating and reducing unequal or unjust impact across the groups a system affects."],
  ["Proxy variable", "A piece of data that stands in for something else. A zip code can act as a proxy for income or ethnicity even when those are never mentioned."],
  ["Privacy", "A person's ability to control their personal information and how it is collected, stored, and used."],
  ["Deepfake", "Synthetic audio, video, or images that imitate a real person's appearance or voice, often to make them seem to say or do something they did not."],
  ["Synthetic media", "Any picture, sound, or video created or heavily altered by AI. Responsible creators label it clearly."],
  ["Misinformation", "False or misleading content, whether shared deliberately or by mistake."],
  ["Recommendation system", "AI that predicts what you might want next, such as the videos, songs, or products an app suggests based on past activity."],
  ["Computer vision", "AI that interprets images and video, used in photo search, face grouping, self-driving features, and medical scan review."],
  ["Academic integrity", "Doing schoolwork honestly: following assignment rules, crediting help, and making sure your work shows your own learning."],
  ["Data center", "A building full of computers that run AI models and online services. Data centers use large amounts of electricity and water for cooling."],
  ["Stakeholder", "Anyone affected by a system or decision, including people who never chose to use it."]
];

export const glossary: GlossaryEntry[] = entries.map(([term, definition]) => ({ term, definition }));
