export const predictorStarters = ["AI can", "A good prompt", "Always check", "The model learned"];

export const predictorCorpus = [
  "AI can find patterns in data.",
  "AI can find patterns in pictures.",
  "AI can find patterns that people miss.",
  "AI can write a first draft.",
  "AI can write a summary of a long article.",
  "AI can make mistakes that sound confident.",
  "AI can make up facts that sound true.",
  "AI can help you study for a test.",
  "AI can help you check your spelling.",
  "AI can sort messages into spam.",
  "AI can be wrong.",
  "A good prompt gives the tool a clear task.",
  "A good prompt gives the tool context.",
  "A good prompt gives an example.",
  "A good prompt names the audience.",
  "A good prompt asks for a format.",
  "A good prompt asks for sources.",
  "Always check the facts with a source.",
  "Always check the facts before you share them.",
  "Always check the answer with a teacher.",
  "Always check the sources it lists.",
  "Always check your work before you submit it.",
  "The model learned patterns from examples.",
  "The model learned patterns from the data it saw.",
  "The model learned from the data it saw.",
  "The model learned to predict the next word.",
  "The model learned bias from the data.",
  "The data it saw was not fair.",
  "The data it saw came from the internet.",
  "The next word is a guess.",
  "A guess can sound confident.",
  "A clear task gets a better answer.",
  "A source can show if a claim is true.",
  "People check the answer.",
  "People decide what to trust."
];
