export type Source = { title: string; publisher: string; url: string; modules: string[]; note: string };

export const sources: Source[] = [
  { title: "AI Index Report", publisher: "Stanford Institute for Human-Centered Artificial Intelligence (HAI)", url: "https://aiindex.stanford.edu/report/", modules: ["foundations", "real-world"], note: "Annual overview of AI capabilities, adoption, and public attitudes used for the big-picture framing of what AI can and cannot do." },
  { title: "Guidance for generative AI in education and research", publisher: "UNESCO", url: "https://www.unesco.org/en/articles/guidance-generative-ai-education-and-research", modules: ["tools", "ethics"], note: "International guidance on age-appropriate, human-centred use of generative AI in schools; informs the study-partner and academic-integrity lessons." },
  { title: "AI Risk Management Framework (AI RMF 1.0)", publisher: "National Institute of Standards and Technology (NIST)", url: "https://www.nist.gov/itl/ai-risk-management-framework", modules: ["ethics", "capstone"], note: "Defines trustworthy-AI characteristics such as validity, fairness, privacy, and accountability that shape the ethics scenarios and capstone plan." },
  { title: "Machine Learning Crash Course", publisher: "Google for Developers", url: "https://developers.google.com/machine-learning/crash-course", modules: ["foundations"], note: "Plain-language explanations of training data, labels, classifiers, accuracy, and overfitting." },
  { title: "Introduction to Large Language Models", publisher: "Google for Developers", url: "https://developers.google.com/machine-learning/resources/intro-llms", modules: ["foundations", "tools"], note: "Explains tokens, next-token prediction, and why fluent output can still be wrong." },
  { title: "Fundamentals of Generative AI", publisher: "Microsoft Learn", url: "https://learn.microsoft.com/training/modules/fundamentals-generative-ai/", modules: ["foundations", "tools"], note: "Introductory material on generative models, prompts, and responsible-use principles." },
  { title: "Responsible AI principles and approach", publisher: "Microsoft", url: "https://www.microsoft.com/en-us/ai/principles-and-approach", modules: ["ethics"], note: "Fairness, reliability, privacy, inclusiveness, transparency, and accountability as a checklist for the ethics module." },
  { title: "Prompt engineering guide", publisher: "OpenAI Platform documentation", url: "https://platform.openai.com/docs/guides/prompt-engineering", modules: ["tools"], note: "Practical prompting strategies: clear instructions, reference text, splitting tasks into steps, and asking for structured output." },
  { title: "Artificial intelligence explainers and reporting", publisher: "MIT Technology Review", url: "https://www.technologyreview.com/topic/artificial-intelligence/", modules: ["foundations", "tools"], note: "Accessible reporting on why chat assistants invent facts and how users can check them." },
  { title: "Deepfakes and synthetic media", publisher: "MIT Media Lab – Detect Fakes project", url: "https://www.media.mit.edu/projects/detect-fakes/overview/", modules: ["ethics"], note: "Research and public-education material on spotting manipulated video and audio." },
  { title: "Algorithmic fairness: Gender Shades", publisher: "MIT Media Lab", url: "https://www.media.mit.edu/projects/gender-shades/overview/", modules: ["foundations", "ethics"], note: "A well-known study showing that face-analysis systems performed unevenly across skin tones and genders." },
  { title: "Artificial Intelligence and Machine Learning in Software as a Medical Device", publisher: "U.S. Food and Drug Administration (FDA)", url: "https://www.fda.gov/medical-devices/software-medical-device-samd/artificial-intelligence-and-machine-learning-software-medical-device", modules: ["real-world"], note: "How medical AI tools are reviewed and why clinicians remain responsible for decisions." },
  { title: "AIFS blog: machine learning in weather forecasting", publisher: "European Centre for Medium-Range Weather Forecasts (ECMWF)", url: "https://www.ecmwf.int/en/about/media-centre/aifs-blog", modules: ["real-world"], note: "Explains how machine-learning models complement physics-based weather forecasting." },
  { title: "Electricity 2024 – Data centres and AI", publisher: "International Energy Agency (IEA)", url: "https://www.iea.org/reports/electricity-2024", modules: ["ethics", "real-world"], note: "Background on data-centre electricity demand used for the environmental-impact lesson." },
  { title: "Children's Online Privacy Protection Rule (COPPA)", publisher: "U.S. Federal Trade Commission", url: "https://www.ftc.gov/legal-library/browse/rules/childrens-online-privacy-protection-rule-coppa", modules: ["ethics"], note: "Why many AI services set age limits and how personal data of young people is protected." },
  { title: "AI Literacy Framework", publisher: "AI4K12 (AAAI & CSTA)", url: "https://ai4k12.org/", modules: ["foundations", "capstone"], note: "The Five Big Ideas in AI for K-12, which guided the learning objectives in the teacher guide." },
  { title: "Understanding AI in Education", publisher: "International Society for Technology in Education (ISTE)", url: "https://iste.org/ai", modules: ["capstone"], note: "Classroom guidance on projects that use AI as a tool while keeping students as the decision-makers." }
];
