import { modules } from "@/content";
import { HeroDial } from "@/components/HeroDial";
import { ModuleList } from "@/components/ModuleList";
import { MagneticButton } from "@/components/motion/MagneticButton";
import { Reveal } from "@/components/motion/Reveal";

export function Hero() {
  return <><section className="relative flex min-h-[92svh] items-center overflow-hidden border-b border-line pt-20"><div className="shell grid w-full min-w-0 items-center gap-8 py-20 lg:grid-cols-12"><div className="relative z-10 min-w-0 lg:col-span-8"><p className="eyebrow"><span className="mr-3 text-accent">00</span> AI literacy for the next generation</p><h1 className="mt-8 max-w-full break-words font-display text-[clamp(2.75rem,9vw,8.5rem)] leading-[.92] tracking-[-.03em]">Find your way through <em className="block text-accent sm:inline">artificial</em> intelligence.</h1><div className="mt-10 grid min-w-0 gap-6 sm:grid-cols-2"><p className="min-w-0 max-w-prose text-lg leading-relaxed text-ink/70">Understand how AI works, practice asking better questions, and decide how you want technology to shape your world.</p><MagneticButton href="#calibrate">Calibrate your compass</MagneticButton></div></div><div className="pointer-events-none absolute -right-24 top-32 hidden w-[55vw] max-w-[620px] opacity-70 sm:block lg:right-0 lg:top-1/2 lg:-translate-y-1/2"><HeroDial /></div></div><div className="absolute bottom-0 left-0 right-0 overflow-hidden border-t border-line py-3"><div className="marquee-track flex w-max gap-8 whitespace-nowrap font-mono text-[10px] uppercase tracking-[.24em] text-ink/65">Foundations · Tools · Ethics · Real world · Capstone · Foundations · Tools · Ethics · Real world · Capstone · Foundations · Tools · Ethics · Real world · Capstone ·</div></div></section><section className="bg-dark py-24 text-paper sm:py-36"><div className="shell grid gap-14 md:grid-cols-3"><Reveal><p className="font-mono text-7xl text-paper/20">01</p><h2 className="mt-7 font-display text-5xl italic">Understand</h2><p className="mt-5 max-w-xs text-paper/60">Build a clear mental model before you build with AI.</p></Reveal><Reveal delay={.08}><p className="font-mono text-7xl text-paper/20">02</p><h2 className="mt-7 font-display text-5xl italic">Practice</h2><p className="mt-5 max-w-xs text-paper/60">Try prompts, scenarios, and projects where your choices matter.</p></Reveal><Reveal delay={.16}><p className="font-mono text-7xl text-paper/20">03</p><h2 className="mt-7 font-display text-5xl italic">Decide</h2><p className="mt-5 max-w-xs text-paper/60">Use curiosity, evidence, and care to choose your next step.</p></Reveal></div></section></>;
}

export function LearningPath() {
  return <section className="shell py-24 sm:py-36"><div className="mb-12 grid gap-6 lg:grid-cols-12"><div className="lg:col-span-7"><p className="eyebrow"><span className="mr-3 text-accent">01</span> The learning path</p><h2 className="mt-6 font-display text-[clamp(2rem,4.5vw,3.75rem)] leading-none">Five directions.<br /><em>One compass.</em></h2></div><p className="self-end text-lg leading-relaxed text-ink/65 lg:col-start-8 lg:col-span-4">Short lessons and hands-on exercises for the questions that matter when everyone is learning what AI can do.</p></div><ModuleList modules={modules} /></section>;
}
