"use client";

import Link from "next/link";
import { motion } from "framer-motion";
import type { Module } from "@/content/types";
import { Reveal } from "@/components/motion/Reveal";
import { ModuleGlyph } from "@/components/ModuleGlyph";

export function ModuleList({ modules, progress = {}, compact = false }: { modules: Module[]; progress?: Record<string, number>; compact?: boolean }) {
  return <div className="divide-y divide-line border-y border-line">{modules.map((module, index) => <Reveal key={module.id} className="group"><motion.div initial="rest" whileHover="hover" className="relative overflow-hidden" data-cursor="open"><motion.span variants={{ rest: { y: "100%" }, hover: { y: 0 } }} transition={{ duration: .45, ease: [0.22, 1, 0.36, 1] }} className="absolute inset-0 bg-ink" /><Link href={`/modules/${module.slug}`} className="relative z-10 flex min-h-[150px] items-center gap-5 overflow-hidden py-7 transition-[padding] duration-500 hover:px-5 sm:min-h-[180px] sm:gap-8 sm:py-8"><motion.span whileHover={{ x: 8 }} className="font-mono text-6xl leading-none text-ink/75 transition-colors group-hover:text-paper/50 sm:text-8xl">{String(index + 1).padStart(2, "0")}</motion.span><span className="min-w-0 flex-1"><span className="mb-2 block font-mono text-[10px] uppercase tracking-[0.2em] text-ink/75 group-hover:text-paper/55">{module.lessons.length} lessons · {module.activity.kind.replace("-", " ")}</span><span className="relative block overflow-hidden font-display text-4xl italic leading-[.9] tracking-tight sm:text-6xl"><motion.span variants={{ rest: { y: 0 }, hover: { y: "-100%" } }} transition={{ duration: .45, ease: [0.22, 1, 0.36, 1] }} className="block">{module.title}</motion.span><motion.span variants={{ rest: { y: "100%" }, hover: { y: 0 } }} transition={{ duration: .45, ease: [0.22, 1, 0.36, 1] }} className="absolute inset-0 block text-paper">{module.title}</motion.span></span>{!compact && <span className="mt-3 block max-w-xl text-sm text-ink/75 group-hover:text-paper/70 sm:text-base">{module.tagline}</span>}</span><ModuleGlyph moduleId={module.id} className="hidden h-10 w-10 shrink-0 transition-transform duration-500 group-hover:rotate-90 sm:block" /><span className="font-mono text-2xl transition-transform duration-300 group-hover:translate-x-2 group-hover:rotate-45">↗</span>{progress[module.id] !== undefined && <span className="absolute bottom-0 left-0 h-0.5 bg-accent transition-all" style={{ width: `${progress[module.id]}%` }} />}</Link></motion.div></Reveal>)}</div>;
}
