"use client";

import Link from "next/link";
import { useState } from "react";
import type { Module } from "@/content/types";
import { useProgress } from "@/state/ProgressProvider";
import { todayKey } from "@/engine/dates";

export function QuizRunner({ module }: { module: Module }) {
  const { dispatch } = useProgress(); const [index, setIndex] = useState(0); const [selected, setSelected] = useState<number | null>(null); const [score, setScore] = useState(0); const [finished, setFinished] = useState(false); const question = module.quiz[index];
  function choose(choice: number) { if (selected !== null) return; setSelected(choice); if (choice === question.answerIndex) setScore((value) => value + 1); }
  function next() { if (index === module.quiz.length - 1) { const finalScore = score; dispatch({ type: "quiz-completed", moduleId: module.id, scorePct: finalScore / module.quiz.length * 100, day: todayKey() }); setFinished(true); } else { setIndex((value) => value + 1); setSelected(null); } }
  function retry() { setIndex(0); setSelected(null); setScore(0); setFinished(false); }
  if (finished) return <div className="border-y border-line py-16 text-center"><p className="eyebrow">Quiz complete</p><h2 className="mt-5 font-mono text-7xl">{Math.round(score / module.quiz.length * 100)}%</h2><p className="mx-auto mt-5 max-w-md text-lg text-ink/65">{score / module.quiz.length >= 0.7 ? "Strong work. Your best score is now saved." : "Review the lessons and try again when you are ready."}</p><div className="mt-8 flex justify-center gap-4"><button className="btn-ghost" onClick={retry}>Retry quiz</button><Link className="btn-pill" href={`/modules/${module.slug}`}>Back to module ↗</Link></div></div>;
  return <div className="border-y border-line py-10"><div className="flex items-center justify-between"><p className="eyebrow">Question {String(index + 1).padStart(2, "0")} / {String(module.quiz.length).padStart(2, "0")}</p><span className="font-mono text-xs text-ink/65">{score} correct</span></div><h2 className="mt-8 max-w-3xl font-display text-4xl leading-tight sm:text-6xl">{question.prompt}</h2><div className="mt-10 border-y border-line">{question.choices.map((choice, choiceIndex) => { const chosen = selected === choiceIndex; const correct = selected !== null && choiceIndex === question.answerIndex; const stateClass = correct ? "border-l-4 !border-l-lime bg-lime/25 pl-4" : chosen ? "border-l-4 !border-l-accent bg-accent/10 pl-4" : ""; return <button key={choice} className={`first:border-t-0 flex w-full items-center gap-5 border-t border-line py-5 text-left transition ${selected === null ? "hover:bg-ink hover:px-5 hover:text-paper" : ""} ${stateClass}`} onClick={() => choose(choiceIndex)}><span className="font-mono text-xs text-ink/65">{String.fromCharCode(65 + choiceIndex)}</span><span className="text-lg">{choice}</span></button>; })}</div>{selected !== null && <div className="mt-8 border-l-2 border-lime pl-5"><p className="font-mono text-xs font-bold uppercase tracking-wider">{selected === question.answerIndex ? "Correct" : "Not quite"}</p><p className="mt-3 max-w-2xl leading-relaxed text-ink/70">{question.explanation}</p><button className="btn-pill mt-6" onClick={next}>{index === module.quiz.length - 1 ? "See results" : "Next question"} ↗</button></div>}</div>;
}
